# zabbix-dovecot
#
# Fixed keys without parameters. Do not convert these into flexible
# UserParameters and do not enable UnsafeUserParameters for this project.

UserParameter=dovecot.stats,/usr/local/scripts/zabbix-dovecot stats
UserParameter=dovecot.version,/usr/local/scripts/zabbix-dovecot version
UserParameter=dovecot.collector.version,/usr/local/scripts/zabbix-dovecot collector-version
