# zabbix-package-updates
#
# Fixed key without parameters. Do not convert this into a flexible
# UserParameter and do not enable UnsafeUserParameters for this project.

UserParameter=linux.package.updates,/usr/bin/sudo -n -- /usr/local/scripts/zabbix-package-updates
